# Generates NSIS installer graphics matching the Inix app / new-tab branding.
param(
  [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$buildDir = Join-Path $ProjectRoot "build"
$logoPath = Join-Path $ProjectRoot "public\logo.png"

if (-not (Test-Path $buildDir)) { New-Item -ItemType Directory -Path $buildDir | Out-Null }
if (-not (Test-Path $logoPath)) { throw "Missing logo: $logoPath" }

function Get-InixColor([int]$R, [int]$G, [int]$B, [int]$A = 255) {
  return [System.Drawing.Color]::FromArgb($A, $R, $G, $B)
}

function Draw-InixBackground {
  param(
    [System.Drawing.Graphics]$G,
    [int]$Width,
    [int]$Height,
    [switch]$Compact
  )

  $G.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
  $G.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
  $G.Clear((Get-InixColor 9 9 14))

  $purple = Get-InixColor 124 106 239 56
  $teal = Get-InixColor 45 212 191 18

  if ($Compact) {
    $G.FillEllipse((New-Object System.Drawing.SolidBrush $purple), -40, -30, $Width + 80, 90)
  }
  else {
    $glowRect = New-Object System.Drawing.RectangleF (-20, -40, ($Width + 40), ($Height * 0.55))
    $path = New-Object System.Drawing.Drawing2D.GraphicsPath
    $path.AddEllipse($glowRect)
    $brush = New-Object System.Drawing.Drawing2D.PathGradientBrush $path
    $brush.CenterColor = (Get-InixColor 124 106 239 90)
    $brush.SurroundColors = @((Get-InixColor 9 9 14 0))
    $centerX = [float]$Width / 2.0
    $brush.CenterPoint = [System.Drawing.PointF]::new($centerX, 40.0)
    $G.FillPath($brush, $path)
    $brush.Dispose()
    $path.Dispose()

    $G.FillEllipse((New-Object System.Drawing.SolidBrush $teal), ($Width * 0.45), ($Height * 0.72), ($Width * 0.7), ($Height * 0.35))
  }
}

function Save-InixSidebar {
  param([string]$OutPath)

  $width = 164
  $height = 314
  $bmp = New-Object System.Drawing.Bitmap $width, $height
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  Draw-InixBackground -G $g -Width $width -Height $height

  $logo = [System.Drawing.Image]::FromFile($logoPath)
  $logoWidth = 118
  $logoHeight = [int]([double]$logo.Height * ($logoWidth / $logo.Width))
  $x = [int](($width - $logoWidth) / 2)
  $y = [int](($height - $logoHeight) / 2)
  $g.DrawImage($logo, $x, $y, $logoWidth, $logoHeight)
  $logo.Dispose()

  $accentPen = New-Object System.Drawing.Pen (Get-InixColor 124 106 239), 2
  $g.DrawLine($accentPen, 24, ($height - 28), ($width - 24), ($height - 28))
  $accentPen.Dispose()

  $bmp.Save($OutPath, [System.Drawing.Imaging.ImageFormat]::Bmp)
  $g.Dispose()
  $bmp.Dispose()
}

function Save-InixHeader {
  param([string]$OutPath)

  $width = 150
  $height = 57
  $bmp = New-Object System.Drawing.Bitmap $width, $height
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  Draw-InixBackground -G $g -Width $width -Height $height -Compact

  $logo = [System.Drawing.Image]::FromFile($logoPath)
  $maxHeight = 38
  $scale = $maxHeight / $logo.Height
  $logoHeight = $maxHeight
  $logoWidth = [int]($logo.Width * $scale)
  $x = [int](($width - $logoWidth) / 2)
  $y = [int](($height - $logoHeight) / 2)
  $g.DrawImage($logo, $x, $y, $logoWidth, $logoHeight)
  $logo.Dispose()

  $accentPen = New-Object System.Drawing.Pen (Get-InixColor 124 106 239), 2
  $g.DrawLine($accentPen, 0, ($height - 2), $width, ($height - 2))
  $accentPen.Dispose()

  $bmp.Save($OutPath, [System.Drawing.Imaging.ImageFormat]::Bmp)
  $g.Dispose()
  $bmp.Dispose()
}

function Save-InixAppIcon {
  param(
    [string]$OutPath,
    [int]$Size = 512,
    [double]$LogoScale = 1.82
  )

  $bmp = New-Object System.Drawing.Bitmap $Size, $Size
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
  $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
  $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
  $g.Clear((Get-InixColor 9 9 14))

  $logo = [System.Drawing.Image]::FromFile($logoPath)
  $drawWidth = [int]($Size * $LogoScale)
  $drawHeight = [int]([double]$logo.Height * ($drawWidth / $logo.Width))
  $x = [int](($Size - $drawWidth) / 2)
  $y = [int](($Size - $drawHeight) / 2)
  $g.DrawImage($logo, $x, $y, $drawWidth, $drawHeight)
  $logo.Dispose()

  $bmp.Save($OutPath, [System.Drawing.Imaging.ImageFormat]::Png)
  $g.Dispose()
  $bmp.Dispose()
}

Save-InixSidebar (Join-Path $buildDir "installerSidebar.bmp")
Copy-Item (Join-Path $buildDir "installerSidebar.bmp") (Join-Path $buildDir "uninstallerSidebar.bmp") -Force
Save-InixHeader (Join-Path $buildDir "installerHeader.bmp")

$iconPng = Join-Path $ProjectRoot "public\icon.png"
Save-InixAppIcon -OutPath $iconPng

Write-Host "App icon PNG written to $iconPng"
Write-Host "Installer assets written to $buildDir (icon.ico is generated by scripts/generate-icon-ico.mjs)"
